name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # 使用正确的版本号
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install weixin
    - name: Set timezone
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
    - name: Test
      run: |
        python your_test_script.py
